# Generated by Django 4.0.3 on 2022-03-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Statuses',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Types',
                'ordering': ('test_type',),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('steps', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testportal.teststatus')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.suite')),
                ('tags', models.ManyToManyField(to='testportal.tag')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testportal.testtype')),
            ],
            options={
                'verbose_name_plural': 'Test Cases',
                'ordering': ('name', 'suite', 'test_type'),
            },
        ),
    ]
