# Generated by Django 4.0.3 on 2022-03-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='TestSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Subcategories',
                'ordering': ('subcategory',),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('steps', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Test is active'), ('depricated', 'Test is depricated'), ('broken', 'Test is broken'), ('under_construction', 'Test is under construction'), ('design', 'Test is in design')], default='design', max_length=128)),
                ('test_type', models.CharField(choices=[('manual', 'Manual Test'), ('automated', 'Automated Test')], default='automated', max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.testcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testportal.testsubcategory')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.suite')),
                ('tags', models.ManyToManyField(to='testportal.tag')),
            ],
            options={
                'verbose_name_plural': 'Test Cases',
                'ordering': ('name', 'suite', 'test_type'),
            },
        ),
    ]
