# Generated by Django 4.0.3 on 2022-05-06 19:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='TestSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Test Subcategories',
                'ordering': ('subcategory',),
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('developers', models.TextField(blank=True, null=True)),
                ('features_to_test', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testportal.suite')),
            ],
            options={
                'verbose_name_plural': 'Test Plans',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('test_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('steps', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Test is active'), ('depricated', 'Test is depricated'), ('broken', 'Test is broken'), ('under-construction', 'Test is under construction'), ('design', 'Test is in design')], default='design', max_length=128)),
                ('test_type', models.CharField(choices=[('manual', 'Manual Test'), ('automated', 'Automated Test')], default='automated', max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.testcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testportal.testsubcategory')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.suite')),
                ('tags', models.ManyToManyField(blank=True, to='testportal.tag')),
                ('test_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testportal.testplan')),
            ],
            options={
                'verbose_name_plural': 'Test Cases',
                'ordering': ('test_case_id', 'name', 'suite', 'test_type'),
                'unique_together': {('suite', 'test_case_id')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('false-negative', 'False Negative'), ('issue', 'Issue'), ('skipped', 'Skipped'), ('under-construction', 'Under Construction'), ('in-documentation', 'In Documentation')], default='skipped', max_length=128)),
                ('note', models.TextField(blank=True, null=True)),
                ('result_date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testportal.testcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Test Results',
                'ordering': ('result_date',),
                'unique_together': {('result_date', 'test_case')},
            },
        ),
    ]
