# Generated by Django 4.0.3 on 2022-03-24 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('developers', models.TextField()),
                ('features_to_test', models.TextField()),
                ('notes', models.TextField()),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testportal.suite')),
            ],
            options={
                'verbose_name_plural': 'Test Plans',
                'ordering': ('name',),
            },
        ),
    ]
