# Generated by Django 4.0.3 on 2022-03-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0003_alter_testplan_description_alter_testplan_developers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testportal.testplan'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('false_negative', 'False Negative'), ('issue', 'Issue'), ('skipped', 'Skipped')], default='skipped', max_length=128)),
                ('result_date', models.DateField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testportal.testcase')),
            ],
            options={
                'verbose_name_plural': 'Test Results',
                'ordering': ('result_date',),
            },
        ),
    ]
