# Generated by Django 4.0.3 on 2022-06-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0004_testcase_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('active', 'Test is active'), ('depricated', 'Test is depricated'), ('broken', 'Test is broken'), ('under-construction', 'Test is under construction'), ('design', 'Test is in design'), ('needs-review', 'Test needs to be reviewed')], default='design', max_length=128),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='testportal.testsubcategory'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testportal.suite'),
        ),
    ]
