# Generated by Django 4.0.3 on 2022-06-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0005_alter_testcase_status_alter_testcase_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='needs_review',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='under_construction',
        ),
    ]
