# Generated by Django 4.0.3 on 2022-06-23 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0006_remove_testcase_needs_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name', 'version'),
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BugVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField(unique=True)),
                ('summary', models.CharField(max_length=512)),
                ('reported_date', models.DateField(default=datetime.datetime.now)),
                ('fixed_date', models.DateField(default=datetime.datetime.now)),
                ('verified_date', models.DateField(default=datetime.datetime.now)),
                ('test', models.CharField(choices=[('gui', 'GUI Test'), ('nongui', 'Non-GUI Test'), ('none', 'No Test')], default='nongui', max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bug_verifications', to='testportal.testcategory')),
                ('products', models.ManyToManyField(blank=True, to='testportal.product')),
            ],
            options={
                'ordering': ('verified_date', 'fixed_date', 'reported_date', 'bug_id'),
            },
        ),
    ]
