# Generated by Django 4.0.3 on 2022-06-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0008_suite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugverification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bug_verifications', to='testportal.testsubcategory'),
        ),
    ]
