# Generated by Django 4.0.3 on 2022-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0009_alter_bugverification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcategory',
            name='category',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='testsubcategory',
            name='subcategory',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
