import random
from datetime import date, timedelta

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from testportal.models import (
    BugVerification,
    Product,
    Suite,
    Tag,
    TestCase,
    TestCategory,
    TestPlan,
    TestResult,
    TestSubcategory,
)


TEST_CASE_STATUSES = [
    'active',
    'depricated',
    'broken',
    'under-construction',
    'design',
    'needs-review',
]

TEST_TYPES = ['manual', 'automated']

RESULT_STATUSES = [
    'pass',
    'fail',
    'false-negative',
    'issue',
    'skipped',
    'under-construction',
    'in-documentation',
]

BUG_TEST_TYPES = ['gui', 'nongui', 'none']


class Command(BaseCommand):
    help = 'Create dummy local data for products, suites, test plans, test cases, results, and bug verifications.'

    def add_arguments(self, parser):
        parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducible dummy data.')
        parser.add_argument('--products', type=int, default=3, help='Number of products to create.')
        parser.add_argument('--suites', type=int, default=4, help='Number of suites to create.')
        parser.add_argument('--cases-per-suite', type=int, default=8, help='Number of test cases per suite.')
        parser.add_argument('--days', type=int, default=14, help='Number of days of test results to generate.')
        parser.add_argument('--bugs', type=int, default=20, help='Number of bug verifications to create.')

    def handle(self, *args, **options):
        random.seed(options['seed'])

        user = self._get_or_create_seed_user()
        categories = self._ensure_categories()
        subcategories = self._ensure_subcategories()
        tags = self._ensure_tags()
        products = self._build_products(options['products'])
        suites = self._build_suites(options['suites'], products)
        plans = self._build_test_plans(suites)

        cases = self._build_test_cases(
            suites=suites,
            plans=plans,
            categories=categories,
            subcategories=subcategories,
            tags=tags,
            cases_per_suite=options['cases_per_suite'],
        )

        result_count = self._build_test_results(cases=cases, user=user, days=options['days'])
        bug_count = self._build_bug_verifications(
            bug_total=options['bugs'],
            subcategories=subcategories,
            products=products,
        )

        self.stdout.write(self.style.SUCCESS('Dummy data seeding complete.'))
        self.stdout.write(
            f'Products: {len(products)} | Suites: {len(suites)} | Plans: {len(plans)} | '
            f'Cases: {len(cases)} | Results: {result_count} | Bugs: {bug_count}'
        )

    def _get_or_create_seed_user(self):
        user_model = get_user_model()
        user, _ = user_model.objects.get_or_create(
            username='seed_user',
            defaults={
                'email': 'seed_user@example.com',
                'is_staff': True,
                'is_superuser': False,
            },
        )
        user.set_password('seed_user')
        user.save(update_fields=['password'])
        return user

    def _ensure_categories(self):
        values = ['Regression', 'Integration', 'Smoke', 'Performance']
        categories = []
        for value in values:
            category, _ = TestCategory.objects.get_or_create(category=value)
            categories.append(category)
        return categories

    def _ensure_subcategories(self):
        values = ['Login', 'Checkout', 'Reporting', 'Billing', 'Settings', 'Notifications']
        subcategories = []
        for value in values:
            subcategory, _ = TestSubcategory.objects.get_or_create(subcategory=value)
            subcategories.append(subcategory)
        return subcategories

    def _ensure_tags(self):
        values = ['critical', 'ui', 'api', 'mobile', 'edge-case', 'fast']
        tags = []
        for value in values:
            tag, _ = Tag.objects.get_or_create(tag=value)
            tags.append(tag)
        return tags

    def _build_products(self, total):
        products = []
        for index in range(1, total + 1):
            product, _ = Product.objects.get_or_create(name=f'Product {index}', version=f'v{index}.0')
            products.append(product)
        return products

    def _build_suites(self, total, products):
        suites = []
        for index in range(1, total + 1):
            suite, _ = Suite.objects.get_or_create(
                name=f'Suite {index}',
                defaults={
                    'active': random.choice([True, True, True, False]),
                    'description': f'Autogenerated suite {index}',
                    'product': random.choice(products) if products else None,
                },
            )
            if suite.product is None and products:
                suite.product = random.choice(products)
                suite.save(update_fields=['product'])
            suites.append(suite)
        return suites

    def _build_test_plans(self, suites):
        plans = []
        for suite in suites:
            plan, _ = TestPlan.objects.get_or_create(
                name=f'{suite.name} Plan',
                suite=suite,
                defaults={
                    'description': f'Test plan for {suite.name}',
                    'developers': 'Alice, Bob',
                    'features_to_test': 'Core flows, edge cases',
                    'notes': 'Seeded for local development',
                },
            )
            plans.append(plan)
        return plans

    def _build_test_cases(self, suites, plans, categories, subcategories, tags, cases_per_suite):
        plans_by_suite_id = {plan.suite_id: plan for plan in plans}
        cases = []
        for suite in suites:
            for index in range(1, cases_per_suite + 1):
                test_case, _ = TestCase.objects.get_or_create(
                    suite=suite,
                    test_case_id=f'TC-{suite.id:02d}-{index:03d}',
                    defaults={
                        'name': f'{suite.name} Case {index}',
                        'notes': 'Generated dummy test case.',
                        'steps': '1. Open app\n2. Perform action\n3. Verify outcome',
                        'category': random.choice(categories),
                        'subcategory': random.choice(subcategories),
                        'test_plan': plans_by_suite_id.get(suite.id),
                        'status': random.choice(TEST_CASE_STATUSES),
                        'test_type': random.choice(TEST_TYPES),
                    },
                )
                if test_case.tags.count() == 0:
                    selected_tags = random.sample(tags, k=random.randint(1, min(3, len(tags))))
                    test_case.tags.set(selected_tags)
                cases.append(test_case)
        return cases

    def _build_test_results(self, cases, user, days):
        today = date.today()
        created_or_updated = 0
        for test_case in cases:
            for day_offset in range(days):
                result_day = today - timedelta(days=day_offset)
                _, _created = TestResult.objects.update_or_create(
                    test_case=test_case,
                    result_date=result_day,
                    defaults={
                        'result': random.choices(
                            population=RESULT_STATUSES,
                            weights=[58, 14, 3, 8, 10, 4, 3],
                            k=1,
                        )[0],
                        'note': 'Generated by seed command',
                        'user': user,
                        'duration': round(random.uniform(1.2, 42.0), 2),
                        'bug_id': str(random.randint(1000, 1200)) if random.random() < 0.18 else None,
                    },
                )
                created_or_updated += 1
        return created_or_updated

    def _build_bug_verifications(self, bug_total, subcategories, products):
        created = 0
        for index in range(1, bug_total + 1):
            bug, _ = BugVerification.objects.get_or_create(
                bug_id=5000 + index,
                defaults={
                    'summary': f'Autogenerated bug {index}',
                    'category': random.choice(subcategories),
                    'test': random.choice(BUG_TEST_TYPES),
                },
            )
            if bug.products.count() == 0 and products:
                selection = random.sample(products, k=random.randint(1, min(2, len(products))))
                bug.products.set(selection)
            created += 1
        return created